//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosphere.ServiceLocating.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplatesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Photosphere.ServiceLocating.Templates.TemplatesResource", typeof(TemplatesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Add({1}, {2});.
        /// </summary>
        internal static string AddToDictinaryStatement {
            get {
                return ResourceManager.GetString("AddToDictinaryStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}({1}).
        /// </summary>
        internal static string NewInstanceStatement {
            get {
                return ResourceManager.GetString("NewInstanceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///{0}
        ///
        ///namespace Photosphere.DependencyInjection.InnerStructure
        ///{{
        ///	internal class {1}ServiceLocator
        ///	{{
        ///		private readonly IDictionary&lt;Type, object&gt; _map = new Dictionary&lt;Type, object&gt;();
        ///
        ///		public {1}ServiceLocator({2})
        ///		{{
        ///            {3}
        ///		}}
        ///
        ///		public T Get&lt;T&gt;() where T : class =&gt; (T) _map[typeof(T)];
        ///	}}
        ///}}
        ///.
        /// </summary>
        internal static string ServiceLocator {
            get {
                return ResourceManager.GetString("ServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using {0};.
        /// </summary>
        internal static string UsingDirective {
            get {
                return ResourceManager.GetString("UsingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var {0} = {1};.
        /// </summary>
        internal static string VariableStatement {
            get {
                return ResourceManager.GetString("VariableStatement", resourceCulture);
            }
        }
    }
}
